apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cluster-standby
  labels:
    app: backend-service
    cluster: standby
spec:
  type: ClusterIP
  selector:
    app: backend-service
    cluster: standby
  ports:
    - name: http
      port: 80
      targetPort: 8080

