apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cluster-hot
  labels:
    app: backend-service
    cluster: hot
spec:
  type: ClusterIP
  selector:
    app: backend-service
    cluster: hot
  ports:
    - name: http
      port: 80
      targetPort: 8080

